lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
]

superlists/urls.py
from django.conf.urls import url, include
# from django.contrib import admin
from lists import views
from lists import urls as list_urls

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^$', views.home_page, name='home'),
    url(r'^lists/', include(list_urls))
    # url(r'^lists/new$', views.new_list, name='new_list'),
    # url(r'^lists/(\d+)/$', views.view_list, name='view_list'),
    # url(r'^lists/(\d+)/add_item$', views.add_item, name='add_item'),
]

lists/models.py
from django.db import models
from django.urls import reverse


class List(models.Model):
    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])


class Item(models.Model):
    text = models.TextField(default='', blank=False)
    list = models.ForeignKey(List, on_delete=models.PROTECT, default=None)

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

    def __str__(self):
        return self.text

lists/forms.py
from django import forms
from lists.models import Item

EMPTY_ITEM_ERROR = "You can't have an empty list item"


class ItemForm(forms.models.ModelForm):

    def save(self, for_list):
        self.instance.list = for_list
        return super().save()

    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(
                attrs={
                    'placeholder': 'Enter a to-do item',
                    'class': 'form-control input-lg',
                }
            )
        }
        error_messages = {
            'text': {'required': EMPTY_ITEM_ERROR}
        }

lists/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ValidationError

from lists.forms import ItemForm
from lists.models import Item, List


def home_page(request):
    return render(request, 'home.html', {'form': ItemForm()})


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ItemForm()

    if request.method == 'POST':
        form = ItemForm(data=request.POST)
        if form.is_valid():
            form.save(for_list=list_)
            return redirect(list_)

    return render(request, 'list.html', {
        'list': list_, 'form': form
    })


def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        list_ = List.objects.create()
        form.save(for_list=list_)
        return redirect(list_)
    else:
        return render(request, 'home.html', {'form': form})

lists/templates/base.html
<!doctype html>
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
        <link href="/static/base.css" rel="stylesheet">

        <title>To-Do lists</title>
    </head>
    <body>
        <div id="container">

            <div class="row">
                <div class="col-md-6 offset-md-3 jumbotron">
                    <div class="text-center">
                        <h1>{% block header_text %}{% endblock %}</h1>
                        <form method="POST" action="{%block form_action%}{%endblock%}">
                            {{ form.text }}
                            {% csrf_token %}
                            {% if form.errors %}
                            <div class="form-group has-error">
                                <span class="help-block">{{ form.text.errors }}</span>
                            </div>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6 offset-md-3">
                    {% block table%}{%endblock%}
                </div>
            </div>

        </div>
    </body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{%block form_action%}{% url 'new_list' %}{%endblock%}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{%block form_action%}{% url 'view_list' list.id %}{%endblock%}

{%block table%}
<table id="id_list_table" class="table">
    {% for item in list.item_set.all %}
        <tr>
            <td>{{ forloop.counter }}: {{ item.text}}</td>
        </tr>
    {% endfor %}
</table>
{%endblock%}